### PR TITLE
Add banner assets to use in the README file

### PR DESCRIPTION
**Pull request by juliofruta**
## Description
I created an assets folder that contains an image and a sketch file for the project

## Motivation and Context
I try to make it so that every repo in the repository contains a cool banner

### CODE REVIEW

**Comment by juanpflores** [comment]
I'm on it

**Review by juanpflores — CHANGES_REQUESTED** [review]
Hey @JuIioCesar 👋 
Do you think you could reference the image on the README file so that we don't have to push another PR?

**Comment by juliofruta** [comment]
👍  Just committed the change

**Comment by juanpflores** [comment]
LGTM 👍

**Review by juanpflores — APPROVED** [review]

**Pull request merged**
